export const MENU_ACCESS = {
  ADMIN_PORTAL: ["ADMIN"],

  DASHBOARD: ["ADMIN", "USER"],
  PROJECT_MANAGEMENT: ["ADMIN", "USER"],
  BOQ_DEFINITION: ["ADMIN", "USER"],
  TENDER_ESTIMATION: ["ADMIN", "USER"],
  COST_CODE_MAPPING: ["ADMIN", "USER"],
  TENDER_FLOATING: ["ADMIN", "USER"],
  TENDER_TRACKING: ["ADMIN", "USER"],

  RECEIVING_OFFERS: ["ADMIN", "USER"],
  TENDER_COMPARISON: ["ADMIN", "USER"],

  CONTRACTOR_ONBOARDING: ["ADMIN", "USER"]
};
